version: '2'
services:
    discovery:
        build: .
        restart: always
        ports:
            - 8080:8080
        # Mac 下无法对外暴露端口
        #network_mode: "host"
        environment:
            # 向注册中心忽略其暴露的端口
            SERVICE_IGNORE: "true"
            # 调试日志
            DEBUG: "dev:*"
