version: '3'
services:
    discovery:
        image: node:8.12
        restart: always
        ports:
            - 8080:8080
        network_mode: host
        environment:
            # 向注册中心忽略其暴露的端口
            SERVICE_IGNORE: "true"
            # 调试日志
            DEBUG: "dev:*"
        volumes:
            - ./src:/usr/src/app
        command: ["node", "/usr/src/app/app.js"]
