version: '3'
services:
    discovery:
        build: .
        restart: always
        ports:
            - 8080:8080
        environment:
            # 向注册中心忽略其暴露的端口
            SERVICE_IGNORE: "true"
            # 调试日志
            DEBUG: "dev:*"
